apiVersion: apps/v1
kind: Deployment
metadata:
  name: greenhouse-kt
  labels:
    app: greenhouse-kt
spec:
  replicas: 2
  selector:
    matchLabels:
      app: greenhouse-kt
  template:
    metadata:
      labels:
        app: greenhouse-kt
    spec:
      containers:
        - name: greenhouse-kt
          image: victorblq/greenhouse-kt:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"

            - name: GREENHOUSE_DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: url

            - name: GREENHOUSE_DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: username

            - name: GREENHOUSE_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: password

            - name: GREENHOUSE_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt
                  key: jwt-secret-key

      imagePullSecrets:
        - name: dockerhub-secret