apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: greenhouse-kt-route
  namespace: greenhouse-kt
spec:
  parentRefs:
    - name: shared-gateway
      namespace: gateway-infra
  hostnames:
    - "greenhouse.local"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: greenhouse-kt-service
          port: 80
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: allow-gateway-to-service
  namespace: greenhouse-kt
spec:
  from:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      namespace: greenhouse-kt
  to:
    - group: ""
      kind: Service