apiVersion: v1
kind: Service
metadata:
  name: greenhouse-kt-service
  namespace: greenhouse-kt
spec:
  selector:
    app: greenhouse-kt
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  type: ClusterIP