name: Build and deploy multi-arch

on:
  push:
    branches: ["master"]

env:
  IMAGE_NAME: "greenhouse-kt"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: amd64
            runner: greenhouse-kt-runner
            platform: linux/amd64
          - arch: arm64
            runner: greenhouse-kt-runner
            platform: linux/arm64
    runs-on: ${{ matrix.runner }}
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install build tools
        run: sudo apt install -y build-essential

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'graalvm'
          cache: 'gradle'

      - name: Build with gradle
        run: |
          chmod +x ./gradlew
          ./gradlew nativeCompile

      - name: Build and push to internal cluster registry
        run: |
          docker buildx build --platform -t registry.arc-systems.svc.cluster.local:5000/greenhouse-app:latest -f ./Dockerfile.native .
          docker push registry.arc-systems.svc.cluster.local:5000/greenhouse-app:latest

      - name: Deploy
        run: |
          kubectl rollout restart deployment/greenhouse-app -n greenhouse --create-namespace
