name: Build and deploy multi-arch

on:
  push:
    branches: ["master"]

jobs:
  build:
    strategy:
      matrix:
        include:
          - arch: amd64
            os-label: X64
          - arch: arm64
            os-label: ARM64
    runs-on: [self-hosted, "${{ matrix.os-label }}"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Native binary
        run: ./gradlew nativeCompile

      - name: Build and push image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/greenhouse-kt:${{ matrix.arch }} .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/greenhouse-kt:${{ matrix.arch }}

  deploy:
    needs: build
    runs-on: [self-hosted, X64] #This one runs on the ubuntu server
    steps:
      - name: Create multi-arch manifest
        run: |
          docker buildx imagetools create -t ${{ secrets.DOCKERHUB_USERNAME }}/greenhouse-kt:latest\
          ${{ secrets.DOCKERHUB_USERNAME }}/greenhouse-kt:amd64 \
          ${{ secrets.DOCKERHUB_USERNAME }}/greenhouse-kt:arm64

      - name: Deploy to kubernetes
        run: |
          kubectl apply -f k8s/
          kubectl rollout restart deployment/greenhouse-kt